server:
  port: 8080

# eureka client
eureka:
  client:
#    register-with-eureka: true
#      fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#    healthcheck:
#      enabled: true

spring:
  profiles:
    active: dev
  application:
    name: apigateway
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        - id: UserApp
          uri: http://localhost:8091/
          predicates:
            - Path=/user/**
        - id: OrderApp
          uri: http://localhost:8092/
          predicates:
            - Path=/order/**
        - id: MenuStatus
          uri: http://localhost:8093/
          predicates:
            - Path=/status/**

  main:
    web-application-type: reactive



# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

